第 3 次 PR。完成遊戲。
MontyPan/T-Chou pull request #5
Opened 2018-11-04 04:28 UTC by cwchou2016

`player` 改成 `player1` 的原因：

* 原本 `player` 是 `int`，所以 `player` 有 1 跟 2 兩個數值。
* 後來因為變數型態改為 `boolean`，所以腦中的想法改為是不是 `player1`。

好啦，我知道很沒有意義，但是不改第一時間腦袋轉不過來......

2018-11-04 06:36 UTC, MontyPan requested changes
### 需求追加 ###

請只用兩個迴圈就解決 `checkWin()`（btw，你現在用了三個，~~這麼多迴圈，你叫我這個迴圈白痴情何以堪 :sob:~~）。

在我腦海裡的版本（aka：我沒有真的寫出來驗證過，所以如果到最後我也寫不出來就要擺兩桌道歉 :dancer: ）需要用到下列招數：

* 取餘數：`%`（這個在上次 PR 當中有示範過）
* `Math.abs(x)`：回傳 x 的絕對值
* 可能要改變傳入的參數

當然這只是預防性提示，如果你完全用不到那也 OK


### Bewared ###

* 你的 50230ad 並不符合「小步前進」的要求，因為他不只是增加 `checkWin`，還包含了修改一堆 JavaDoc

2018-11-04 06:36 UTC, MontyPan commented on TicTacToe/src/us/dontcareabout/chou/ticTacToe/Main.java
> +	 * Return true when player wins
### Must FIX ###
＝＝" 之前不就已經說了，請不要留下無意義的 comment（尤其是 IDE 生成的），對我來說 L40～L43 都是沒意義的。

其他請比照辦理

2018-11-06 12:28 UTC, cwchou2016 commented
Updated!

2018-11-07 02:35 UTC, MontyPan reviewed
奇怪了，為什麼之前的 commit 全部不見了？為什麼你要把 branch 清掉重來？（而且疑似還用了 `--force` 的招數？）

> # 請不要在發 PR 之後對該 branch 作 `--force` （或類似）的動作 #

基本上除非我有 reject PR，不然大多數時候都是繼續 commit 下去。如果對 git 這部份操作有問題，請在 meeting 的時候提出。

然後，你太會帳面上符合需求的招數了（我都不知道該稱讚還是噴飯...），所以我只好正面迎戰了 :smiling_imp: 。


### 需求追加 ###

請用「N 子棋」的規則來重寫 **整個程式** 。

N 子棋是說玩家若在四個方向當中有任意一個方向有連續 N 個都是自己的棋子就獲勝。井字遊戲就是 N=3 時的版本（這裡不考慮其他規則，例如正式的五子棋有禁手、六子棋一次下兩手等規定）

請在 L6 之前寫

```Java
public static final int N = 3;
```

然後在所有 method（包含 main）當中直接使用 N 來代替 3

注意：

* 你可以無視之前提到「`checkWin()` 當中只能用兩個迴圈」的限制。
* 除了宣告 `N` 之外，程式當中不能出現 0 / 1 以外的數字（不包含變數名稱啦）。
    * 理論上應該不用，如果你真的走投無路，可以先丟上來看看。

請慢用...... [撚鬚長笑]

2018-11-07 02:35 UTC, MontyPan commented on TicTacToe/src/us/dontcareabout/chou/ticTacToe/Main.java
> +		boolean checkRow = true, checkColumn = true;
這在 Java 圈當中普遍認為是不良的 coding style。Java 圈內習慣 / 喜歡每個變數獨立宣告（一方面是這樣才方便寫 JavaDoc）

2018-11-08 12:52 UTC, cwchou2016 commented
Updated!

> 基本上除非我有 reject PR，不然大多數時候都是繼續 commit 下去。如果對 git 這部份操作有問題，請在 meeting 的時候提出。

對不起，以後會注意。

2018-11-08 13:42 UTC, MontyPan reviewed
### Must FIX ###

> 除了宣告 N 之外，程式當中不能出現 0 / 1 以外的數字（不包含變數名稱啦）。 

你這個版本還是有一堆 0 / 1 以外的數字，例如 L24、還有那精美的 `getPosition()`。

喔對，上次忘記講，這有個專有名詞來講這些「散落在程式碼裡頭、乍看之下會不知道為什麼要用這個數字」的狀況，叫做「magic number」


### Bewared ###

麻煩一次就把 coding style 寫正確好嗎？為什麼在 81033bf 的時候沒有檢查到、然後 dd52cdb 的時候才發現（那不會 `git reset` 回去重作喔 [飛踢]）

2018-11-08 13:42 UTC, MontyPan commented on TicTacToe/src/us/dontcareabout/chou/ticTacToe/Main.java
> +		playBoard = new char[N][N];
寫成兩行有比較厲害嗎？ O.o

2018-11-08 14:41 UTC, cwchou2016 commented
Updated!

2018-11-08 14:51 UTC, MontyPan commented
不行，不能讓你再逃了。你必須要用原來「只輸入一次 position」的方法來完成 `getPosition()`

2018-11-09 11:05 UTC, cwchou2016 commented
Updated!

2018-11-09 13:13 UTC, MontyPan commented
真的非常會找洞鑽（恭喜你取得泥鰍的封號 ＝＝"），可是我明明說的是「要用原來只輸入一次 position的方法」。如果你已經忘記你原來是寫啥（靠，自己回頭看 commit 阿幹），那我很明確地說：

> # 只能輸入一個數字 #

至於這個數字是 0～8 還是 1～9 就看你開心。

2018-11-09 13:22 UTC, MontyPan commented
光顧著阻擋泥鰍入侵都忘記講了... :scream:  

你這個 commit 問題很多，這裡純粹先 FYI，**後續修正還是以[上一個 comment](https://github.com/MontyPan/T-Chou/pull/5#issuecomment-437355701) 為主**

* 現在的 `getInputNumber()` 犯了掛羊頭賣狗肉的問題
* 要作兩次 `input.split()`、還產生兩個 String[]，從效率上的觀點不是好事情
    * 當然現在 JIT 很可怕，不知道會不會對這種東西作最佳化。（JIT 不 到就算啦 Zzzz）
* git 的 commit message 習俗是第一行不能超過 80 個字、第二行空白。

2018-11-11 03:14 UTC, cwchou2016 commented
Updated!

2018-11-11 11:31 UTC, MontyPan commented on TicTacToe/src/us/dontcareabout/chou/ticTacToe/Main.java
> +		int row = N - 1 - ((input - 1) / N);
請解釋一下這行的邏輯，我實在看不懂...... Orz

2018-11-11 13:37 UTC, cwchou2016 commented on TicTacToe/src/us/dontcareabout/chou/ticTacToe/Main.java
> +		int row = N - 1 - ((input - 1) / N);
把輸入的數字﹙1-9﹚轉換成 row。

* 先把 1-9 減 1 轉成 0-8，然後除 3 取整數。
* 但是數字鍵的順序是由下往上，跟 array 的 row 編號相反，
 所以用 2 減，把 0, 1, 2 轉成 2, 1, 0。

2018-11-11 14:03 UTC, MontyPan commented on TicTacToe/src/us/dontcareabout/chou/ticTacToe/Main.java
> +		int row = N - 1 - ((input - 1) / N);
＝＝" （在程式設計師之間）這樣問的時候，通常不是要問「這行的執行過程是什麼」，而是問你「為什麼要這樣寫」

所以重點是那句「但是數字鍵的順序是由下往上」，坦白說我就更不懂了，於是我終於去執行你的程式 & 考古了一下.... 結論是你怎麼講都不對... :smiling_imp: 

1. 你沒在改版的時候把印座標的部份拔掉（這件事情本身就可以是個 bug）
1. 你現在座標順序還是由上而下

所以我看不懂是理所當然的... :rage: 

當然你要說這樣這樣的話（？），我預先回頭去考古了一下，在 1f94d06 的時候，你的 input 值跟棋盤的對應關係的確就是你說的「由下往上」沒錯，但其實沒有太大意義（我可以跟你先壓 1000 元，除了我之外你大概很難遇到會自己回頭翻舊帳確認的人.... [挖鼻孔]），更別說使用者絕對會認為這是 bug。

這個 line note 先停在這邊，下面會有正式的 review comment 告訴你還要改哪些（嗯，我又聽到遙遠的地方傳來咒罵聲 :dancer: ）

2018-11-11 14:17 UTC, MontyPan commented
### Must FIX ###

你現在有足夠的知識可以回頭把那個該死的 `checkWin()` 縮減到 20 行以內。

建議回頭回憶一下[第一個 comment]( https://github.com/MontyPan/T-Chou/pull/5#pullrequestreview-171350575)，搭配服用。


### 需求追加 ###

請把畫面改成

```
X| |        1|2|3
-+-+-       -+-+-
 |O|        4|5|6
-+-+-       -+-+-
 | |X       7|8|9
```

左邊是實際的棋盤、右邊是輸入位置對應提示圖。兩個井字之間的空格數在 4～10 之間均可（看你的美感認定 :see_no_evil:）。btw，你可以直接假設 console 的顯示字型是 monospace 類的字型。

另外，作這個需求追加的時候，請確保你的程式碼夠簡短而且好讀 :dancer:

2018-11-18 04:06 UTC, cwchou2016 commented
Updated!

-----------------------------------------------------------------------

`checkWin()` 我還是縮不到20行內 = =

2018-11-19 03:35 UTC, MontyPan commented
### Must FIX ###
* 除了下面列出的 method，你不能使用其他的 method，也就是說，要的話你得自己寫
    * System.out.print()
    * System.out.println()（其實可以用上面那個代替 Zzzz）
    * String.valueOf()（其實古老都是用字串相加就算了）

### Import Notice ###
* 如果我的人肉 computer 沒有算錯，你的 516a73e 根本不是什麼 minor。你製造了一個無窮迴圈但是在 c0af4b3 卻完全沒發現？
* 該是來改善你的 commit message 了，請不要再打什麼「modified method xxx」，這是個二級廢話，距離「有講跟沒講一樣」只有一步之遙，你要講的是「為什麼要修改」。不然你有辦法只看 commit message 告訴我 7a5a1e8 跟 06a8886 差在哪裡？
    * 新增 / 刪除東西這樣寫就無可厚非。但是有超過 87% 的 commit 都是修改。

### Bewared ###
* 即使你用了 `Arrays.fill()` 之類的招數，你的程式碼還是很冗長，老人家看不懂 :see_no_evil: 
* 我看到了一堆 `System.out.printf()`，所以你就有了新功課 #8  :smiling_imp:

2018-11-21 14:20 UTC, cwchou2016 commented
Updated!

2018-11-22 02:48 UTC, MontyPan reviewed
看來你目前的極限就是這樣了 ~~，然後我有點厭倦繼續看這個程式了 [捏鼻]~~

只能靠 #7 這類練習來彌補了，說到這個， #7 發了也快一個禮拜了，怎麼完全無聲無息咧？ [敲碗] 那個應該一個小時就能生出一個版本吧？

anyway，請注意下面兩個 line note 裡頭的 **bewared**

然後你應該詰譙我上一個 comment 把 `important notice` 打成 `import notice`  [指]（遙遠的聲音：幹這也要怪我？）

2018-11-22 02:48 UTC, MontyPan commented on TicTacToe/src/us/dontcareabout/chou/ticTacToe/Main.java
> +			msg += charArray[idx];
### Bewared ###
這是一個 Java 經典炸點，就是沒事不要在 for 迴圈當中作字串相加。應該要改用 `StringBuffer` 或是 `StringBuilder`。

不過你現在這樣搞無訪，先知道有這件事情就好。

2018-11-22 02:48 UTC, MontyPan commented on TicTacToe/src/us/dontcareabout/chou/ticTacToe/Main.java
> +				msg += sep;
### Bewared ###
你這個 if 寫得太多餘了....

2018-11-22 02:49 UTC, merged